name: PortalTeleport
version: '${project.version}'
main: org.dreaght.portalteleport.PortalTeleport
author: Dreaght
description: Plugin for making portals that can be used to teleport everywhere!
api-version: '1.18'
commands:
  portal:
    description: Portal management